package com.kodilla.exception;

import com.kodilla.exception.test.ExceptionHandling;

public class SecondChallengeException extends ExceptionHandling {
}